tvim:
    year: 2019
    number: 2
    total number: 43
    protocol number: 2
    protocol day: 15
    protocol month: 5
    protocol month name: мая
    protocol year: 2009
path:
    articles: articles_2019_2
    resources: resources
    docs: docs
    output: output
