tvim:
    year: 2020
    number: 1
    total number: 46
    protocol number: ??
    protocol day: ??
    protocol month: ??
    protocol month name: ????
    protocol year: ????
path:
    articles: articles_2020_1
    resources: resources
    docs: docs
    output: output
